# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_nPUaln9aR_mNq1ildX80BItZQFvnMv
"""

def calculate_tax(income):
    if income <= 5000:
        return 0
    elif income <= 10000:
        return (income - 5000) * 0.10
    else:
        return 5000 * 0.10 + (income - 10000) * 0.20


def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True


class User:
    def __init__(self, username):
        self.username = username

    def is_admin(self):
        return self.username == "admin"


def send_welcome_email(email):
    print(f"Sending email to {email}")


import requests
def fetch_user():
    return requests.get("https://api.example.com/user").json()


from datetime import datetime
def is_weekend():
    return datetime.now().weekday() >= 5


import re
def is_strong(password):
    return len(password) >= 8 and any(c.isdigit() for c in password)


def clean_input(s):
    return s.strip().lower().replace(" ", "_")