# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_nPUaln9aR_mNq1ildX80BItZQFvnMv
"""

from main import *
from unittest.mock import patch, Mock

def test_calculate_tax():
    assert calculate_tax(3000) == 0
    assert calculate_tax(7000) == 200.0
    assert calculate_tax(12000) == 900.0


def test_is_prime():
    assert not is_prime(1)
    assert is_prime(2)
    assert not is_prime(4)


def test_user():
    assert User("admin").is_admin()
    assert not User("guest").is_admin()


@patch('builtins.print')
def test_send_email(mock_print):
    send_welcome_email("test@example.com")
    mock_print.assert_called_with("Sending email to test@example.com")


@patch('main.requests.get')
def test_fetch_user(mock_get):
    mock_response = Mock()
    mock_response.json.return_value = {"name": "Jack"}
    mock_get.return_value = mock_response

    assert fetch_user() == {"name": "Jack"}


@patch('main.datetime')
def test_is_weekend(mock_datetime):
    mock_datetime.now.return_value = Mock(weekday=lambda: 5)
    assert is_weekend()


def test_password():
    assert is_strong("abcd1234")
    assert not is_strong("abc")


def test_clean_input():
    assert clean_input(" Hello World ") == "hello_world"